--- #YAML:1.0
name:                Net-Shoutcast-Admin
version:             0.01
abstract:            administration of Shoutcast servers
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    LWP::UserAgent:                0
    Test::More:                    0
    URI::Escape:                   0
    version:                       0
    XML::Simple:                   0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - David Precious <davidp@preshweb.co.uk>
